name: Playwright Tests

on:
  push:
    branches: [main, master, nirghosh]

  pull_request:
    branches: [main, master]

    # Run automatically every day at 5:30 PM India time
  schedule:
    - cron: '00 18 * * *'
      timezone: 'Asia/Kolkata'

  workflow_dispatch:
    inputs:
      test_target:
        description: 'Enter Nane or Tags:'
        required: true
        default: '@smoke'
        type: string
        

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Download project code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Install only Chromium browser
      - name: Install Chromium
        run: npx playwright install --with-deps chromium

                  # Manual execution: run the entered file name or tag
      - name: Run selected Playwright file or tag
        if: github.event_name == 'workflow_dispatch'
        env:
          CI: true
          PLAYWRIGHT_HTML_OPEN: never
          TEST_TARGET: ${{ inputs.test_target }}
        run: |
          if [[ "$TEST_TARGET" == @* ]]; then
            echo "Running tests with tag: $TEST_TARGET"
            npx playwright test --project=chromium --grep "$TEST_TARGET" --reporter=html
          elif [[ "$TEST_TARGET" == *.spec.ts ]]; then
            echo "Running test file: $TEST_TARGET"
            npx playwright test "tests/tests/$TEST_TARGET" --project=chromium --reporter=html
          else
            echo "Invalid input: $TEST_TARGET"
            echo "Enter a file like Cart.spec.ts or a tag like @smoke"
            exit 1
          fi

      # Automatic push/PR: execute the 10 smoke tests
      - name: Run Playwright smoke tests
        if: github.event_name != 'workflow_dispatch'
        env:
          CI: true
          PLAYWRIGHT_HTML_OPEN: never
        run: npx playwright test --project=chromium --grep "@smoke" --reporter=html

      # Create ZIP of the latest report
      - name: Create Playwright report ZIP
        if: always()
        run: |
          if [ -d "playwright-report" ]; then
            zip -r playwright-report.zip playwright-report
          else
            mkdir -p playwright-report
            echo "Playwright report was not generated." > playwright-report/report-not-generated.txt
            zip -r playwright-report.zip playwright-report
          fi

      # Save report in GitHub Actions
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Send ZIP report through Gmail
      - name: Send Playwright report by email
        if: always()
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: 'Playwright GitHub Actions <${{ secrets.MAIL_USERNAME }}>'
          to: ${{ secrets.MAIL_TO }}
          subject: 'Playwright Test Report - ${{ job.status }}'
          body: |
            Hello,

            Playwright test execution has finished.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Selected test: ${{ inputs.test_file || '10 smoke tests' }}
            Status: ${{ job.status }}
            Run number: ${{ github.run_number }}

            GitHub Actions URL:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            The latest Playwright HTML report is attached.
            attachments: playwright-report/index.html
